package com.healthlife.aicoach.controller;

import com.healthlife.aicoach.service.AiCoachService;
import com.healthlife.common.dto.aicoach.*;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

@RestController
@RequestMapping("/api/v1/ai")
@RequiredArgsConstructor
@Validated
public class AiCoachController {

    private final AiCoachService aiCoachService;

    /**
     * Standard chat — returns the full response once complete.
     * Use {@link #chatStream} for real-time streaming.
     */
    @PostMapping("/chat")
    public ResponseEntity<ChatResponse> chat(@Valid @RequestBody ChatRequest request) {
        return ResponseEntity.ok(aiCoachService.chat(request));
    }

    /**
     * Streaming chat via Server-Sent Events (SSE).
     * The client receives tokens as they are generated by DeepSeek.
     * Connect with: {@code EventSource('/api/v1/ai/chat/stream')}
     */
    @PostMapping(value = "/chat/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public SseEmitter chatStream(@Valid @RequestBody ChatRequest request) {
        return aiCoachService.chatStream(request);
    }

    @GetMapping("/insights/daily")
    public ResponseEntity<InsightDto> getDailyInsight() {
        return ResponseEntity.ok(aiCoachService.getDailyInsight());
    }

    @GetMapping("/insights/weekly")
    public ResponseEntity<InsightDto> getWeeklyInsight() {
        return ResponseEntity.ok(aiCoachService.getWeeklyInsight());
    }

    @GetMapping("/predictions/energy")
    public ResponseEntity<InsightDto> getEnergyPrediction() {
        return ResponseEntity.ok(aiCoachService.getEnergyPrediction());
    }

    @GetMapping("/predictions/symptoms")
    public ResponseEntity<InsightDto> getSymptomPrediction() {
        return ResponseEntity.ok(aiCoachService.getSymptomPrediction());
    }

    @GetMapping("/recommendations")
    public ResponseEntity<InsightDto> getRecommendations() {
        return ResponseEntity.ok(aiCoachService.getRecommendations());
    }

    @PostMapping("/analyze/correlations")
    public ResponseEntity<InsightDto> analyzeCorrelations() {
        return ResponseEntity.ok(aiCoachService.analyzeCorrelations());
    }
}
